### ISSUE TITLE
load_in_8bit is not working for some huggingface model

### ISSUE THREAD

**Issue by sanyalsunny111** [TimDettmers/bitsandbytes#14]
I have updated the transformers package and I am using ViLT model: https://huggingface.co/docs/transformers/model_doc/vilt#transformers.ViltForQuestionAnswering

![image](https://user-images.githubusercontent.com/36811567/185273480-63ad1a32-de8c-46f2-9b7f-b871c51ad04e.png)

I am getting this error is load_in_8bit is not integrated will all hugging face models ? Could you please let me know how to use load_in_8bit for any huggingface model not just BLOOM and T5.

![image](https://user-images.githubusercontent.com/36811567/185273985-086cb27e-eb67-4ed9-b3d1-9478b55838d8.png)

**Comment by younesbelkada** [comment]
Hi @sanyalsunny111 
Thank you very much for your message
Your initial issue is related to the fact that you did not installed the main branch of `transformers`. Since the new features of the library has not been released yet, you have to manually install its latest version by running:
`pip install git+https://github.com/huggingface/transformers.git`
However, this model does not support `device_map=auto` yet. This should be addressed in the PR: https://github.com/huggingface/transformers/pull/18683 therefore available as soon as the fix will be validated. 
If you want to use this feature you can directly use it and test it, you can directly download the `transformers` version that contains the ViLT support. I made an example colab that you can try out [here](https://colab.research.google.com/drive/1_vq6tlT12lLt2-w6O-HbCxPAulQ4O4Be?usp=sharing)
Let me know if anything else is unclear!

**Comment by sanyalsunny111** [comment]
@younesbelkada Thank you for your previous response. you rightly mentioned device map auto is not supported yet and without that we cannot run a 8 bit model. But my question is how you have used `device_map="auto` in the colab link you have shared in your previous comment?
![image](https://user-images.githubusercontent.com/36811567/185459406-2efac1c2-2e26-4f1b-bef8-94553d1e99b5.png)

**Comment by younesbelkada** [comment]
Hi @sanyalsunny111 
If you follow the same installation guidelines as on the google colab I shared you, you should be able to pass "device_map=auto" without any problems

**Comment by sanyalsunny111** [comment]
Hi @younesbelkada thank you for helping me out. I have followed your installation process you have mentioned above.   Here is my code.
![image](https://user-images.githubusercontent.com/36811567/185670000-887f1d91-bb23-41bc-b6a6-5d10fd95c388.png)

But I am still getting same error could you please suggest any solution?

![image](https://user-images.githubusercontent.com/36811567/185670172-262742de-f6d8-42bd-b540-16aebc9a18d0.png)

**Comment by younesbelkada** [comment]
Hi @sanyalsunny111 !
No worries, I think that you still didn't installed the correct version because you have your previous `transformers` that you probably did not removed. 
Could you try this command? `pip install --force git+https://github.com/younesbelkada/transformers.git@eee3986ec37e3050c1ee94a63efb13090602eae5`
Thanks!

**Comment by sanyalsunny111** [comment]
Hey @younesbelkada Thank you very much sir. It is working fine.

**Comment by younesbelkada** [comment]
Great ! Very happy that you made it work? 💪 Do not hesitate to open an issue if you face into any new issue

**Comment by sanyalsunny111** [comment]
Hey @younesbelkada the device_map='auto' is actually affecting the distributed data parallel (DDP). I am using 8 GPUs and trying to run a faster inference. Here is the error I am getting `model = ViltForQuestionAnswering.from_pretrained("dandelin/vilt-b32-finetuned-vqa", device_map="auto",
                                                         load_in_8bit=True)`
![image](https://user-images.githubusercontent.com/36811567/185693611-f2358fc9-1483-44ff-bf8b-710078d8496e.png)

Could you please suggest how to use load_in_8bit with DDP?

**Comment by younesbelkada** [comment]
Hi @sanyalsunny111 
Thanks for your message!
Did the error happen also with "load_in_8bit=False"? Could you also share the full script to reproduce the issue?
Thanks

**Comment by sanyalsunny111** [comment]
Yes, with `load_in_8bit=False` this error happened code attached screenshot-1. 
![image](https://user-images.githubusercontent.com/36811567/185705841-81f4d37d-f0e0-406d-8ff7-76ecc4056fb7.png)
Now when I am not using `load_in_8bit` at all no error is happening so, it's safe to assume either device_map or load_in_8bit is causing the error. [Here ](https://colab.research.google.com/drive/1GUqGMK8z3S8bLD3IKzHLzq929HsMuhJY?usp=sharing) is my piece of code and [here ](https://github.com/NielsRogge/Transformers-Tutorials/blob/master/ViLT/Fine_tuning_ViLT_for_VQA.ipynb) is the hugging face tutorial which my code is based upon.
